global:
  message: Welcome to customer service dev environment!!

server:
  port: 8082

message: Hello from Dev!

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/customer_master
    username: postgres
    password: passer123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
