spring:
  application:
    name: order-service
  datasource:
    url: jdbc:h2:mem:order_master
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    database-platform: org.hibernate.dialect.H2Dialect

# H2 Console Configuration (optional)
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: false
