global:
  message: "Welcome to order service prod environment!!"

server:
  port: 8085

message: "Hello from Order Prod!"

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:5432/order_prod
    username: postgres
    password: "passer123"
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 2000
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        jdbc.batch_size: 20
        order_inserts: true
        order_updates: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when_authorized
      probes:
        enabled: true

logging:
  level:
    root: INFO
    org.hibernate.SQL: WARN
    org.hibernate.type: WARN
